package Tower;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cell.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




public class Cell
{
	private boolean busy;
	private Map map;
	private ArrayList<Cell> neighbours;
	protected enum CellType {Terrain, Road, StartPoint, EndPoint};
	private CellType celltype;
	
	//Constructors
	public Cell(boolean b, Map map, CellType ct)
	{
		this.busy = b;
		this.map = map;
		this.neighbours = new ArrayList<Cell>();
		this.celltype = ct;
	}
	
	//Getter
	public boolean getBusy()
	{
		return this.busy;
	}
	
	public Map getMap()
	{
		return this.map;
	}
	
	public ArrayList<Cell> getNeighbours()
	{
		return this.neighbours;
	}

	//Setter
	public void setBusy(boolean b)
	{
		this.busy = b;
	}

	public Obstacle setObstacle()
	{
		Obstacle ob = new Obstacle(0, 0);
		return ob;
	}

}
