import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




public abstract class Item
{
	private int maxMagicStoneNumber;
	private Cell position; //Cellat hogyan adjuk át konstruktorban???
	private ArrayList<MagicStone> magicStones;
	
	//Constructor
	public Item(int mm)
	{
		this.maxMagicStoneNumber = mm;
		this.magicStones = new ArrayList<MagicStone>();
	}
	
	//Getter
	public int getMaxMagicStoneNumber()
	{
		return this.maxMagicStoneNumber;
	}
	
	public Cell getPosition()
	{
		return this.position;
	}
	
	public ArrayList<MagicStone> getMagicStone()
	{
		return this.magicStones;
	}
	
	//Setter
	public void setMaxMagicStoneNumber(int mm)
	{
		this.maxMagicStoneNumber = mm;
	}
	
	public void setMagicStone(ArrayList<MagicStone> ms)
	{
		this.magicStones = (ArrayList<MagicStone>)ms.clone();
	}
	
	public abstract boolean upgrade(MagicStone stone);
}

