import java.util.HashMap;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MagicStone.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




public class MagicStone
{
	public String name;
	public int firePower;
	public int attackSpeed;
	public int range;
	public double slowRate;
	public HashMap<String, Integer> bonusPowers;
	public HashMap<String, Integer> bonusSlowRates;
	
	public MagicStone(String n, int fp, int as, int r, double sr)
	{
		//szerintem ide kéne a switchcase szerkezet de most nem látom!!! (enegyenlõre így írom meg hogy forduljon)
		this.name = n; //Ez így jó vagy konstruktorosan??
		this.firePower = fp;
		this.attackSpeed = as;
		this.range = r;
		this.slowRate = sr;
		this.bonusPowers = new HashMap<String, Integer>();
		this.bonusSlowRates = new HashMap<String, Integer>();
	}
	
	//Getter
	public String getName()
	{
		return this.name;
	}
	
	public int getFirePower()
	{
		return this.firePower;
	}
	
	public int getAttackSpeed()
	{
		return this.attackSpeed;
	}
	
	public int getRang()
	{
		return this.range;
	}
	
	public double getslowRate()
	{
		return this.slowRate;
	}
	
	public HashMap<String, Integer> getBonusPowers()
	{
		return this.bonusPowers;
	}
	
	public HashMap<String, Integer> getBonusSlowRate()
	{
		return this.bonusSlowRates;
	}
	
	//Setter
	public void setName(String n)
	{
		this.name = n;
	}
	
	public void setFirePower(int fp)
	{
		this.firePower = fp;
	}
	
	public void setAttackSpeed(int as)
	{
		this.attackSpeed = as;
	}
	
	public void setRang(int r)
	{
		this.range = r;
	}
	
	public void getslowRate(double sr)
	{
		this.slowRate = sr;
	}
	
	public void getBonusPowers(HashMap<String, Integer> bonusp)
	{
		this.bonusPowers = (HashMap<String, Integer>)bonusp.clone();
	}
	
	public void getBonusSlowRate(HashMap<String, Integer> bonuss)
	{
		this.bonusSlowRates = (HashMap<String, Integer>)bonuss.clone();
	}
}
