package Model;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map.Entry;

import Model.Map.Direction;
import View.CellView;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cell.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//



/**
 * A palya egy egysege.
 */
public class Cell
{
	/**
	 * Map.Entry absztrakt osztaly implementacioja.
	 * @param <K> A kulcs tipusa
	 * @param <V> Az ertek tipusa
	 */
	public final static class CellEntry<K, V> implements java.util.Map.Entry<K, V> {
		private final K key;
		private V value;
		
		public CellEntry(K key, V value) {
			this.key = key;
			this.value = value;
		}
		
		@Override
		public K getKey() {
			return key;
		}

		@Override
		public V getValue() {
			return value;
		}

		@Override
		public V setValue(V value) {
			V oldValue = this.value;
			this.value = value;
			return oldValue;
		}
		
	}
	
	/**
	 * A cella soranak azonositoja, amely fenntrol lefele, 0-tol kezdodoen szamozodik.
	 */
	private int rowId;
	/**
	 * A cella oszlopanak azonositoja, amely balrol jobbra, 0-tol kezdodoen szamozodik.
	 */
	private int columnId;
	/**
	 * A cellat megjelenito CellView referenciaja.
	 */
	private CellView view;
	/**
	 * A cella foglaltsaga.
	 */
	private boolean busy;
	/**
	 * A cellat tartalmazo Map objektum.
	 */
	private Map map;
	/**
	 * A cella szomszedai.
	 * Minden szomszedhoz tartozik egy boolean ertek, amely jelzi, hogy
	 *  tovabb lehet-e lepni a cellara.
	 */
	private HashMap<Direction, Entry<Cell, Boolean>> neighbours;
	/**
	 * Egy cella lehetseges tipusait tartalmazo enumeracio.
	 */
	public enum CellType {
		Terrain, Road, StartPoint, EndPoint
	};
	/**
	 * A cella tipusa.
	 */
	private CellType type;

	/**
	 * Konstruktor. A foglaltsag allapota false lesz alapbol.
	 * @param map  A cellat tartalmazo Map objektum.
	 * @param ct  A cella tipusa.
	 */
	public Cell(Map map, CellType ct)
	{
		this.busy = false;
		this.map = map;
		this.neighbours = new HashMap<Direction, Entry<Cell, Boolean>>();
		this.type = ct;
		
		// CellView letrehozasa
		view = new CellView(this);
	}

	/**
	 * Getter a rowId attributumra.
	 * @return  A rowId attributum.
	 */
	public int getRowId()
	{
		return this.rowId;
	}
	
	/**
	 * Getter a columnId attributumra.
	 * @return  A columnId attributum.
	 */
	public int getColumnId()
	{
		return this.columnId;
	}
	
	/**
	 * Getter a view attributumra.
	 * @return  A view attributum.
	 */
	public CellView getView()
	{
		return this.view;
	}
	
	/**
	 * Getter a busy attributumra.
	 * @return  A busy attributum.
	 */
	public boolean getBusy()
	{
		return this.busy;
	}

	/**
	 * Getter a map attributumra.
	 * @return  A map attributum.
	 */
	public Map getMap()
	{
		return this.map;
	}

		public CellType getCellType()
	{
		return this.type;
	}

	/**
	 * Getter a neighbours attributumra.
	 * @return  A neighbours attributum.
	 */
	public HashMap<Direction, Entry<Cell, Boolean>> getNeighbours()
	{
		return this.neighbours;
	}

	/**
	 * Visszaadja a cellan talalhato akadalyt. Ha nincs akadaly a cellan
	 *  akkor null-t ad vissza.
	 * @return A cellan talalhato akadaly vagy null.
	 */
	public Obstacle getObstacle()
	{
		Obstacle returnValue = null;
		ArrayList<Obstacle> obstacles = map.getObstacles();
		for(Obstacle obstacle: obstacles) {
			if(obstacle.getPosition() == this) {
				returnValue = obstacle;
				break;
			}
		}

		return returnValue;
	}
	
	/**
	 * Visszaadja a cellan talalhato tornyot. Ha nincs torony a cellan
	 *  akkor null-t ad vissza.
	 * @return A cellan talalhato torony vagy null.
	 */
	public Tower getTower()
	{
		Tower returnValue = null;
		ArrayList<Tower> towers = map.getTowers();
		for(Tower tower: towers) {
			if(tower.getPosition() == this) {
				returnValue = tower;
				break;
			}
		}

		return returnValue;
	}
	
	/**
	 * Visszaadja a cellan talalhato ellensegeket. Ha nincs ellenseg a cellan
	 *  akkor null-t ad vissza.
	 * @return A cellan talalhato ellensegek listaja vagy null.
	 */
	public ArrayList<Enemy> getEnemys()
	{
		ArrayList<Enemy> returnValue = new ArrayList<Enemy>();
		ArrayList<Enemy> enemies = map.getEnemies();
		for(Enemy enemy: enemies) {
			if(enemy.getPosition() == this) {
				returnValue.add(enemy);
			}
		}

		if (returnValue.isEmpty()) {
			return null;
		}
		else {
			return returnValue;
		}
	}

	/**
	 * Setter a rowId attributumra.
	 * @param b  A rowId attributum kivant erteke.
	 */
	public void setRowId(int rowId)
	{
		this.rowId = rowId;
	}
	
	/**
	 * Setter a columnId attributumra.
	 * @param b  A columnId attributum kivant erteke.
	 */
	public void setColumnId(int columnId)
	{
		this.columnId = columnId;
	}
	
	/**
	 * Setter a view attributumra.
	 * @param b  A view attributum kivant erteke.
	 */
	public void setView(CellView view)
	{
		this.view = view;
	}
	
	/**
	 * Setter a busy attributumra.
	 * @param b  A busy attributum kivant erteke.
	 */
	public void setBusy(boolean b)
	{
		this.busy = b;
	}

	/**
	 * Setter a neighbours attributumra.
	 * @param b  A neighbours attributum kivant erteke.
	 */
	public void setNeighbours(HashMap<Direction, Entry<Cell, Boolean>> n) {
		this.neighbours = n;
	}
}
