package Tower;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cell.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//



/**
 * A palya egy egysege.
 */
public class Cell
{
	/**
	 * A cella foglaltsaga.
	 */
	private boolean busy;
	/**
	 * A cellat tartalmazo Map objektum.
	 */
	private Map map;
	/**
	 * A cella szomszedai.
	 */
	private ArrayList<Cell> neighbours;
	/**
	 * Egy cella lehetseges tipusait tartalmazo enumeracio.
	 */
	protected enum CellType {Terrain, Road, StartPoint, EndPoint};
	/**
	 * A cella tipusa.
	 */
	private CellType celltype;
	
	/**
	 * Konstruktor.
	 * @param b  A foglaltsag allapota.
	 * @param map  A cellat tartalmazo Map objektum.
	 * @param ct  A cella tipusa.
	 */
	public Cell(boolean b, Map map, CellType ct)
	{
		this.busy = b;
		this.map = map;
		this.neighbours = new ArrayList<Cell>();
		this.celltype = ct;
	}
	
	/**
	 * Getter a busy attributumra.
	 * @return  A busy attributum.
	 */
	public boolean getBusy()
	{
		String logString = "Cell.getBusy()";
		Logger.Log(1, logString, this);

		Logger.Log(0, logString, this);
		return this.busy;
	}

	/**
	 * Getter a map attributumra.
	 * @return  A map attributum.
	 */
	public Map getMap()
	{
		return this.map;
	}

	/**
	 * Getter a neighbours attributumra.
	 * @return  A neighbours attributum.
	 */
	public ArrayList<Cell> getNeighbours()
	{
		return this.neighbours;
	}

	/**
	 * Visszaadja a cellan talalhato akadalyt.
	 * @return A cellan talalhato akadaly.
	 */
	public Obstacle getObstacle()
	{
		String logString = "Cell.getObstacle()";
		Logger.Log(1, logString, this);

		Obstacle returnValue = null;
		ArrayList<Obstacle> obstacles = map.getObstacles();
		for(Obstacle obstacle: obstacles) {
			if(obstacle.getPosition() == this) {
				returnValue = obstacle;
				break;
			}
		}

		Logger.Log(0, logString, this);
		return returnValue;
	}

	/**
	 * Setter a busy attributumra.
	 * @param b  A busy attributum kivant erteke.
	 */
	public void setBusy(boolean b)
	{
		this.busy = b;
	}

}
