package Tower;
import java.util.HashMap;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Elf.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




/**
 * Elf ellenség.
 */
public class Elf extends Enemy
{
	/**
	 * Konstruktor.
	 * @param hp  Életerõ.
	 * @param as  Az aktuális sebesség.
	 * @param os  Az eredeti, lassítás nélküli sebesség.
	 * @param m  Az ellenség halálakor szarumánhoz kerülõ varázserõ.
	 * @param lt  Az az idõpont amikor az ellenség legutoljára lépett.
	 */
	public Elf(int hp, int as, int os, int m, long lt) {
		super(hp, as, os, m, lt);
	}

	public boolean damage(int power, HashMap<String,Integer> bonus)
	{
		return true;
	}
	
	public void move()
	{
	
	}
}
