package Tower;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GreenMagicStone.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//



/**
 * Zold varazsko.
 */
public class GreenMagicStone extends MagicStone
{
	/**
	 * Konstruktor. Peldanyositashoz ajanlott ezt hasznalni.
	 * Default parameterekkel jon letre a zold ko. 
	 */
	public GreenMagicStone() {
		this(
				"green",	// A varazsko neve 
				100,	// Power bonus
				100, 	// Speed bonus
				100, 	// Range bonus
				100		// Slowrate bonus
				);
	}
	
	/**
	 * Konstruktor.
	 * @param n  A varazsko neve.
	 * @param fp  Egy torony sebzesi erejenek novelese.
	 * @param as  Egy torony tamadasi sebessegenek novelese.
	 * @param r  Egy torony lotavolsaganak novelese.
	 * @param sr  Egy akadaly lassitasi szorzojanak novelese.
	 */
	public GreenMagicStone(String n, int fp, int as, int r, double sr) {
		super(n, fp, as, r, sr);
	}
}
