package Tower;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GreenMagicStone.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




public class GreenMagicStone extends MagicStone
{

	public GreenMagicStone(String n, int fp, int as, int r, double sr) {
		super(n, fp, as, r, sr);
	}
	//Lásd purplemagicstone
}
