package Tower;
import java.util.HashMap;
import java.util.Scanner;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hobbit.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




/**
 * Hobbit ellenseg.
 */
public class Hobbit extends Enemy
{
	/**
	 * Konstruktor.
	 * @param hp  eletero.
	 * @param as  Az aktualis sebesseg.
	 * @param os  Az eredeti, lassitas nelkuli sebesseg.
	 * @param m  Az ellenseg halalakor szarumanhoz kerulo varazsero.
	 * @param lt  Az az idopont amikor az ellenseg legutoljara lepett.
	 */
	public Hobbit(int hp, int as, int os, int m, long lt) {
		super(hp, as, os, m, lt);
	}

	public boolean damage(int power, HashMap<String, Integer> bonus)
	{
		return true;
	}

	public void move()
	{
		String logString = "Hobbit.move()";
		Logger.Log(1, logString, this);

		String answerText;
		boolean isSlowed = false;
		Obstacle obstacle;
		Cell cell;
		Scanner scanner = new Scanner (System.in);

		// Kivalasztjuk a kovetkezo cellat, amire lepni fog az ellenseg
		cell = this.getPosition().getNeighbours().get(0);

		this.setPosition(cell);

		cell.getBusy();

		// Felhasznaloi interakcio
		if(Program.usecaseNumber==4) {
			while(true) {
				System.out.print("Akadalyra lepett [igen, nem]: ");
				answerText = scanner.next();
				if(answerText.equals("igen")) {
					isSlowed=true;
					break;
				} else if(answerText.equals("nem")) {
					isSlowed=false;
					break;
				} else {
					System.out.println("Helytelen ertek");
					continue;
				}
			}
		}

		if(isSlowed) {
			obstacle = cell.getObstacle();
			obstacle.getSlowRate();
			obstacle.getBonusSlowRates();
			this.setActualSpeed(1);
		} else {
			this.setActualSpeed(this.getOriginalSpeed());
		}

		Logger.Log(0, logString, this);
	}
}
