package Tower;
import java.util.HashMap;
import java.util.Scanner;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hobbit.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




public class Hobbit extends Enemy
{
	public Hobbit(int hp, int as, int os, int m, long lt) {
		super(hp, as, os, m, lt);
	}

	public boolean damage(int power, HashMap<String, Integer> bonus)
	{
		return true;
	}

	public void move()
	{
		String logString = "Hobbit.move()";
		Logger.Log(1, logString, this);

		String answerText;
		boolean isSlowed;
		Obstacle obstacle;
		Scanner scanner = new Scanner (System.in);

		this.getPosition().getBusy();

		while(true) {
			System.out.print("Akadalyra lepett [igen, nem]: ");
			answerText = scanner.next();
			if(answerText.equals("igen")) {
				isSlowed=true;
				break;
			} else if(answerText.equals("nem")) {
				isSlowed=false;
				break;
			} else {
				System.out.println("Helytelen ertek");
				continue;
			}
		}

		if(isSlowed) {
			obstacle = this.getPosition().getObstacle();
			obstacle.getSlowRate();
			obstacle.getBonusSlowRates();
		}

		Logger.Log(0, logString, this);
	}
}
