package Tower;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




public abstract class Item
{
	private int maxMagicStoneNumber;
	private Cell position;
	private ArrayList<MagicStone> magicStones;

	//Constructor
	public Item(int mm, Cell pos)
	{
		this.maxMagicStoneNumber = mm;
		this.magicStones = new ArrayList<MagicStone>();
		this.position = pos;
	}

	//Getter
	public int getMaxMagicStoneNumber()
	{
		return this.maxMagicStoneNumber;
	}

	public Cell getPosition()
	{
		String logString = "Item.getPosition()";
		Logger.Log(1, logString, this);

		Logger.Log(0, logString, this);
		return this.position;
	}

	public ArrayList<MagicStone> getMagicStone()
	{
		return this.magicStones;
	}

	//Setter
	public void setMaxMagicStoneNumber(int mm)
	{
		this.maxMagicStoneNumber = mm;
	}

	public void setMagicStone(ArrayList<MagicStone> ms)
	{
		this.magicStones = ms;
	}

	public abstract boolean upgrade(MagicStone stone);
}

