package Tower;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




/**
 * A pályára rakható objektumok összefoglaló absztrakt õsosztály.
 */
public abstract class Item
{
	/**
	 * Az objektumra rakható varázskövek maximális száma.
	 */
	private int maxMagicStoneNumber;
	/**
	 * Az objektum pozíciója.
	 */
	private Cell position;
	/**
	 * Az objektumra helyezett varázskövek listája.
	 */
	private ArrayList<MagicStone> magicStones;
	
	/**
	 * Konstruktor.
	 * @param mm  Az objektumra rakható varázskövek maximális száma.
	 * @param pos  Az objektum pozíciója.
	 */
	public Item(int mm, Cell pos)
	{
		this.maxMagicStoneNumber = mm;
		this.magicStones = new ArrayList<MagicStone>();
		this.position = pos;
	}

	/**
	 * Getter a maxMagicStoneNumber attribútumra.
	 * @return  A maxMagicStoneNumber attribútum.
	 */
	public int getMaxMagicStoneNumber()
	{
		return this.maxMagicStoneNumber;
	}

	/**
	 * Getter a position attribútumra.
	 * @return  A position attribútum.
	 */
	public Cell getPosition()
	{
		String logString = "Item.getPosition()";
		Logger.Log(1, logString, this);

		Logger.Log(0, logString, this);
		return this.position;
	}
/**
	 * Getter a magicStones attribútumra.
	 * @return  A magicStones attribútum.
	 */
	public ArrayList<MagicStone> getMagicStone()
	{
		return this.magicStones;
	}
	
	/**
	 * Setter a maxMagicStoneNumber attribútumra.
	 * @param b  A maxMagicStoneNumber attribútum kívánt értéke.
	 */
	public void setMaxMagicStoneNumber(int mm)
	{
		this.maxMagicStoneNumber = mm;
	}
	
	/**
	 * Setter a magicStones attribútumra.
	 * @param b  A magicStones attribútum kívánt értéke.
	 */
	public void setMagicStone(ArrayList<MagicStone> ms)
	{
		this.magicStones = (ArrayList<MagicStone>)ms.clone();
	}
	
	/**
	 * Fejleszti az objektumot.
	 * @param stone  A varázskõ.
	 * @return A fejlesztés sikeressége.
	 */
	public abstract boolean upgrade(MagicStone stone);
}



