package Tower;
import java.util.HashMap;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MagicStone.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




/**
 * A varazskovek ososztalya.
 */
public class MagicStone
{
	/**
	 * A varazsko neve.
	 */
	public String name;
	/**
	 * Egy torony sebzesi erejenek novelese.
	 */
	public int firePower;
	/**
	 * Egy torony tamadasi sebessegenek novelese.
	 */
	public int attackSpeed;
	/**
	 * Egy torony lotavolsaganak novelese.
	 */
	public int range;
	/**
	 * Egy akadaly lassitasi szorzojanak novelese.
	 */
	public double slowRate;
	/**
	 * Az egyes ellenseg tipusokra vonatkozo sebzesi ero novelesek torony eseten.
	 */
	public HashMap<String, Integer> bonusPowers;
	/**
	 * Az egyes ellenseg tipusokra vonatkozo lassitasi szorzo novelesek akadaly eseten.
	 */
	public HashMap<String, Double> bonusSlowRates;
	
	/**
	 * Konstruktor.
	 * @param n  A varazsko neve.
	 * @param fp  Egy torony sebzesi erejenek novelese.
	 * @param as  Egy torony tamadasi sebessegenek novelese.
	 * @param r  Egy torony lotavolsaganak novelese.
	 * @param sr  Egy akadaly lassitasi szorzojanak novelese.
	 */
	public MagicStone(String n, int fp, int as, int r, double sr)
	{
		//szerintem ide kene a switchcase szerkezet de most nem latom!!! (enegyelore igy irom meg hogy forduljon)
		this.name = n; //Ez igy jo vagy konstruktorosan??
		this.firePower = fp;
		this.attackSpeed = as;
		this.range = r;
		this.slowRate = sr;
		this.bonusPowers = new HashMap<String, Integer>();
		this.bonusSlowRates = new HashMap<String, Double>();
	}
	
	/**
	 * Getter a name attributumra.
	 * @return  A name attributum.
	 */
	public String getName()
	{
		return this.name;
	}
	
	/**
	 * Getter a firePower attributumra.
	 * @return  A firePower attributum.
	 */
	public int getFirePower()
	{
		return this.firePower;
	}
	
	/**
	 * Getter az attackSpeed attributumra.
	 * @return  Az attackSpeed attributum.
	 */
	public int getAttackSpeed()
	{
		return this.attackSpeed;
	}
	
	/**
	 * Getter a range attributumra.
	 * @return  A range attributum.
	 */
	public int getRange()
	{
		return this.range;
	}
	
	/**
	 * Getter a slowRate attributumra.
	 * @return  A slowRate attributum.
	 */
	public double getSlowRate()
	{
		return this.slowRate;
	}
	
	/**
	 * Getter a bonusPowers attributumra.
	 * @return  A bonusPowers attributum.
	 */
	public HashMap<String, Integer> getBonusPowers()
	{
		return this.bonusPowers;
	}
	
	/**
	 * Getter a bonusSlowRates attributumra.
	 * @return  A bonusSlowRates attributum.
	 */
	public HashMap<String, Double> getBonusSlowRate()
	{
		return this.bonusSlowRates;
	}
	
	/**
	 * Setter a name attributumra.
	 * @param hp  A name attributum kivant erteke.
	 */
	public void setName(String n)
	{
		this.name = n;
	}
	
	/**
	 * Setter a firePower attributumra.
	 * @param hp  A firePower attributum kivant erteke.
	 */
	public void setFirePower(int fp)
	{
		this.firePower = fp;
	}
	
	/**
	 * Setter az attackSpeed attributumra.
	 * @param hp  Az attackSpeed attributum kivant erteke.
	 */
	public void setAttackSpeed(int as)
	{
		this.attackSpeed = as;
	}
	
	/**
	 * Setter a range attributumra.
	 * @param hp  A range attributum kivant erteke.
	 */
	public void setRange(int r)
	{
		this.range = r;
	}
	
	/**
	 * Setter a slowRate attributumra.
	 * @param hp  A slowRate attributum kivant erteke.
	 */
	public void setSlowRate(double sr)
	{
		this.slowRate = sr;
	}
	
	/**
	 * Setter a bonusPowers attributumra.
	 * @param hp  A bonusPowers attributum kivant erteke.
	 */
	public void setBonusPowers(HashMap<String, Integer> bonusp)
	{
		this.bonusPowers = bonusp;
	}
	
	/**
	 * Setter a bonusSlowRates attributumra.
	 * @param hp  A bonusSlowRates attributum kivant erteke.
	 */
	public void setBonusSlowRate(HashMap<String, Double> bonuss)
	{
		this.bonusSlowRates = bonuss;
	}
}
