package Tower;
import java.util.HashMap;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MagicStone.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




/**
 * A varazskovek ososztalya..
 */
public class MagicStone
{
	/**
	 * A varazsko neve.
	 */
	public String name;
	/**
	 * Egy torony sebzesi erejenek novelese.
	 */
	public int firePower;
	/**
	 * Egy torony tamadasi sebessegenek novelese.
	 */
	public int attackSpeed;
	/**
	 * Egy torony lotavolsaganak novelese.
	 */
	public int range;
	/**
	 * Egy akadaly lassitasi szorzojanak novelese.
	 */
	public double slowRate;
	/**
	 * Az egyes ellenseg tipusokra vonatkozo sebzesi ero novelesek torony eseten.
	 */
	public HashMap<String, Integer> bonusPowers;
	/**
	 * Az egyes ellenseg tipusokra vonatkozo lassitasi szorzo novelesek akadaly eseten.
	 */
	public HashMap<String, Integer> bonusSlowRates;
	
	/**
	 * Konstruktor.
	 * @param n  A varazsko neve.
	 * @param fp  Egy torony sebzesi erejenek novelese.
	 * @param as  Egy torony tamadasi sebessegenek novelese.
	 * @param r  Egy torony lotavolsaganak novelese.
	 * @param sr  Egy akadaly lassitasi szorzojanak novelese.
	 */
	public MagicStone(String n, int fp, int as, int r, double sr)
	{
		//szerintem ide kene a switchcase szerkezet de most nem latom!!! (enegyelore igy irom meg hogy forduljon)
		this.name = n; //Ez igy jo vagy konstruktorosan??
		this.firePower = fp;
		this.attackSpeed = as;
		this.range = r;
		this.slowRate = sr;
		this.bonusPowers = new HashMap<String, Integer>();
		this.bonusSlowRates = new HashMap<String, Integer>();
	}
	
	// Ezeket meg nem kommenteztem mert szerintem itt nincs szukseg getter/setterekre.
	// A varazsko eleve csak egy leiro osztaly kb egy struct is lehetne es minden attributuma
	// publikus szoval szuksegtelen kulon getter hozza.
	public String getName()
	{
		return this.name;
	}
	
	public int getFirePower()
	{
		return this.firePower;
	}
	
	public int getAttackSpeed()
	{
		return this.attackSpeed;
	}
	
	public int getRange()
	{
		return this.range;
	}
	
	public double getSlowRate()
	{
		return this.slowRate;
	}
	
	public HashMap<String, Integer> getBonusPowers()
	{
		return this.bonusPowers;
	}
	
	public HashMap<String, Integer> getBonusSlowRate()
	{
		return this.bonusSlowRates;
	}
	
	//Setter
	public void setName(String n)
	{
		this.name = n;
	}
	
	public void setFirePower(int fp)
	{
		this.firePower = fp;
	}
	
	public void setAttackSpeed(int as)
	{
		this.attackSpeed = as;
	}
	
	public void setRange(int r)
	{
		this.range = r;
	}
	
	public void setSlowRate(double sr)
	{
		this.slowRate = sr;
	}
	
	public void setBonusPowers(HashMap<String, Integer> bonusp)
	{
		this.bonusPowers = bonusp;
	}
	
	public void setBonusSlowRate(HashMap<String, Integer> bonuss)
	{
		this.bonusSlowRates = bonuss;
	}
}
