package Tower;
import java.util.HashMap;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MagicStone.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




/**
 * A varázskövek õsosztálya..
 */
public class MagicStone
{
	/**
	 * A varázskõ neve.
	 */
	public String name;
	/**
	 * Egy torony sebzési erejének növelése.
	 */
	public int firePower;
	/**
	 * Egy torony támadási sebességének növelése.
	 */
	public int attackSpeed;
	/**
	 * Egy torony lõtávolságának növelése.
	 */
	public int range;
	/**
	 * Egy akadály lassítási szorzójának növelése.
	 */
	public double slowRate;
	/**
	 * Az egyes ellenség típusokra vonatkozó sebzési erõ növelések torony esetén.
	 */
	public HashMap<String, Integer> bonusPowers;
	/**
	 * Az egyes ellenség típusokra vonatkozó lassítási szorzó növelések akadály esetén.
	 */
	public HashMap<String, Integer> bonusSlowRates;
	
	/**
	 * Konstruktor.
	 * @param n  A varázskõ neve.
	 * @param fp  Egy torony sebzési erejének növelése.
	 * @param as  Egy torony támadási sebességének növelése.
	 * @param r  Egy torony lõtávolságának növelése.
	 * @param sr  Egy akadály lassítási szorzójának növelése.
	 */
	public MagicStone(String n, int fp, int as, int r, double sr)
	{
		//szerintem ide kéne a switchcase szerkezet de most nem látom!!! (enegyelõre így írom meg hogy forduljon)
		this.name = n; //Ez így jó vagy konstruktorosan??
		this.firePower = fp;
		this.attackSpeed = as;
		this.range = r;
		this.slowRate = sr;
		this.bonusPowers = new HashMap<String, Integer>();
		this.bonusSlowRates = new HashMap<String, Integer>();
	}
	
	// Ezeket még nem kommenteztem mert szerintem itt nincs szükség getter/setterekre.
	// A varázskõ eleve csak egy leíró osztály kb egy struct is lehetne és minden attribútuma
	// publikus szóval szükségtelen külön getter hozzá.
	public String getName()
	{
		return this.name;
	}
	
	public int getFirePower()
	{
		return this.firePower;
	}
	
	public int getAttackSpeed()
	{
		return this.attackSpeed;
	}
	
	public int getRange()
	{
		return this.range;
	}
	
	public double getSlowRate()
	{
		return this.slowRate;
	}
	
	public HashMap<String, Integer> getBonusPowers()
	{
		return this.bonusPowers;
	}
	
	public HashMap<String, Integer> getBonusSlowRate()
	{
		return this.bonusSlowRates;
	}
	
	//Setter
	public void setName(String n)
	{
		this.name = n;
	}
	
	public void setFirePower(int fp)
	{
		this.firePower = fp;
	}
	
	public void setAttackSpeed(int as)
	{
		this.attackSpeed = as;
	}
	
	public void setRange(int r)
	{
		this.range = r;
	}
	
	public void setSlowRate(double sr)
	{
		this.slowRate = sr;
	}
	
	public void setBonusPowers(HashMap<String, Integer> bonusp)
	{
		this.bonusPowers = bonusp;
	}
	
	public void setBonusSlowRate(HashMap<String, Integer> bonuss)
	{
		this.bonusSlowRates = bonuss;
	}
}
