package Tower;
import java.util.HashMap;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Obstacle.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




public class Obstacle extends Item
{
	private double slowRate;
	private HashMap<String, Double> bonusSlowRates;
	
	//Constructor
	public Obstacle(double sr, int mm, Cell pos)
	{
		super(mm, pos);
		this.slowRate = sr;
		bonusSlowRates = new HashMap<String,Double>();
	}
	
	//Getter
	public double getSlowRate()
	{
		String logString = "Obstacle.getSlowRate()";
		Logger.Log(1, logString, this);

		Logger.Log(0, logString, this);
		return this.slowRate;
	}
	
	public HashMap<String,Double> getBonusSlowRates()
	{
		String logString = "Obstacle.getBonusSlowRates()";
		Logger.Log(1, logString, this);

		Logger.Log(0, logString, this);
		return this.bonusSlowRates;
	}
	
	//Setter
	public void setSlowRate(double sr)
	{
		this.slowRate = sr;
	}
	
	public void setBonusSlowRates(HashMap<String,Double> bonus)
	{
		this.bonusSlowRates = bonus;
	}
	
	public boolean upgrade(MagicStone stone)
	{
		String logString = "Obstacle.upgrade(stone)";
		Logger.Log(1, logString, this);
		
		Logger.Log(0, logString, this);
		return true;
	}
}
