package Tower;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PurpleMagicStone.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//



/**
 * Lila varazsko.
 */
public class PurpleMagicStone extends MagicStone
{
	/**
	 * Konstruktor.
	 * @param n  A varazsko neve.
	 * @param fp  Egy torony sebzesi erejenek novelese.
	 * @param as  Egy torony tamadasi sebessegenek novelese.
	 * @param r  Egy torony lotavolsaganak novelese.
	 * @param sr  Egy akadaly lassitasi szorzojanak novelese.
	 */
	public PurpleMagicStone(String n, int fp, int as, int r, double sr) {
		super(n, fp, as, r, sr);
		// TODO Auto-generated constructor stub
	}
	//Itt is irjunk speci konstruktort?
}
