package Tower;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PurpleMagicStone.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




public class PurpleMagicStone extends MagicStone
{

	public PurpleMagicStone(String n, int fp, int as, int r, double sr) {
		super(n, fp, as, r, sr);
		// TODO Auto-generated constructor stub
	}
	//Itt is írjunk spéci konstruktort?
}
