package Tower;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Round.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




public class Round
{
	private int enemyNumber;
	private int enemyAddingTime;
	private double enemyNumberMultiplier;
	private double enemyAddingTimeMultiplier;
	private int roundTime;
	private int maxRounds;
	
	public Round(int en, int et, double enm, double etm, int rt, int mr){
		
		this.enemyNumber = en;
		this.enemyAddingTime = et;
		this.enemyNumberMultiplier = enm;
		this.enemyAddingTimeMultiplier = etm;
		this.roundTime = rt;
		this.maxRounds = mr;
	}
	
	//Getter
	public int getEnemyNumber()
	{
		return this.enemyNumber;
	}
	
	public int getEnemyAddingTime()
	{
		return this.enemyAddingTime;
	}
	
	public double getEnemyNumberMultiplier()
	{
		return this.enemyNumberMultiplier;
	}
	
	public double getEnemyAddingTimeMultiplier()
	{
		return this.enemyAddingTimeMultiplier;
	}
	
	public int getRoundTime()
	{
		return this.roundTime;
	}
	
	public int getMaxRounds()
	{
		return this.maxRounds;
	}
	
	//Setter
	public void setEnemyNumber(int en)
	{
		this.enemyNumber = en;
	}
	
	public void setEnemyAddingTime(int et)
	{
		this.enemyAddingTime = et;
	}
	
	public void setEnemyNumberMultiplier(double enm)
	{
		this.enemyNumberMultiplier = enm;
	}
	
	public void setEnemyAddingTimeMultiplier(double etm)
	{
		this.enemyAddingTimeMultiplier = etm;
	}
	
	public void setRoundTime(int rt)
	{
		this.roundTime = rt;
	}
	
	public void setMaxRounds(int mr)
	{
		this.maxRounds =  mr;
	}
}
