package Tower;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Round.java
//  @ Date : 2014.03.20.
//  @ Author : 
//
//




/**
 * A jatek egy korenek leiroja.
 */
public class Round
{
	/**
	 * Az adott idokozonkent a palyahoz adando ellensegek szama.
	 */
	private int enemyNumber;
	/**
	 * Ennyi idonkent kell hozzaadni ellenfeleket a palyahoz.
	 */
	private int enemyAddingTime;
	/**
	 * Az enemyNumber attributumot minden kor vegen ennyivel kell szorozni.
	 */
	private double enemyNumberMultiplier;
	/**
	 * Az enemyAddingTime attributumot minden kor vegen ennyivel kell szorozni.
	 */
	private double enemyAddingTimeMultiplier;
	/**
	 * A kor ennyi ideig tart.
	 */
	private int roundTime;
	/**
	 * osszesen ennyi kor lesz.
	 */
	private int maxRounds;
	
	/**
	 * Konstruktor.
	 * @param en  Az adott idokozonkent a palyahoz adando ellensegek szama.
	 * @param et  Ennyi idonkent kell hozzaadni ellenfeleket a palyahoz.
	 * @param enm  Az enemyNumber attributumot minden kor vegen ennyivel kell szorozni.
	 * @param etm  Az enemyAddingTime attributumot minden kor vegen ennyivel kell szorozni.
	 * @param rt  A kor ennyi ideig tart.
	 * @param mr  osszesen ennyi kor lesz.
	 */
	public Round(int en, int et, double enm, double etm, int rt, int mr){
		
		this.enemyNumber = en;
		this.enemyAddingTime = et;
		this.enemyNumberMultiplier = enm;
		this.enemyAddingTimeMultiplier = etm;
		this.roundTime = rt;
		this.maxRounds = mr;
	}
	
	/**
	 * Getter az enemyNumber attributumra.
	 * @return  Az enemyNumber attributum.
	 */
	public int getEnemyNumber()
	{
		return this.enemyNumber;
	}
	
	/**
	 * Getter az enemyAddingTime attributumra.
	 * @return  Az enemyAddingTime attributum.
	 */
	public int getEnemyAddingTime()
	{
		return this.enemyAddingTime;
	}
	
	/**
	 * Getter az enemyNumberMultiplier attributumra.
	 * @return  Az enemyNumberMultiplier attributum.
	 */
	public double getEnemyNumberMultiplier()
	{
		return this.enemyNumberMultiplier;
	}
	
	/**
	 * Getter az enemyAddingTimeMultiplier attributumra.
	 * @return  Az enemyAddingTimeMultiplier attributum.
	 */
	public double getEnemyAddingTimeMultiplier()
	{
		return this.enemyAddingTimeMultiplier;
	}
	
	/**
	 * Getter a roundTime attributumra.
	 * @return  A roundTime attributum.
	 */
	public int getRoundTime()
	{
		return this.roundTime;
	}
	
	/**
	 * Getter a maxRounds attributumra.
	 * @return  A maxRounds attributum.
	 */
	public int getMaxRounds()
	{
		return this.maxRounds;
	}
	
	/**
	 * Setter az enemyNumber attributumra.
	 * @param b  Az enemyNumber attributum kivant erteke.
	 */
	public void setEnemyNumber(int en)
	{
		this.enemyNumber = en;
	}
	
	/**
	 * Setter az enemyAddingTime attributumra.
	 * @param b  Az enemyAddingTime attributum kivant erteke.
	 */
	public void setEnemyAddingTime(int et)
	{
		this.enemyAddingTime = et;
	}
	
	/**
	 * Setter az enemyNumberMultiplier attributumra.
	 * @param b  Az enemyNumberMultiplier attributum kivant erteke.
	 */
	public void setEnemyNumberMultiplier(double enm)
	{
		this.enemyNumberMultiplier = enm;
	}
	
	/**
	 * Setter az enemyAddingTimeMultiplier attributumra.
	 * @param b  Az enemyAddingTimeMultiplier attributum kivant erteke.
	 */
	public void setEnemyAddingTimeMultiplier(double etm)
	{
		this.enemyAddingTimeMultiplier = etm;
	}
	
	/**
	 * Setter a roundTime attributumra.
	 * @param b  A roundTime attributum kivant erteke.
	 */
	public void setRoundTime(int rt)
	{
		this.roundTime = rt;
	}
	
	/**
	 * Setter a maxRounds attributumra.
	 * @param b  A maxRounds attributum kivant erteke.
	 */
	public void setMaxRounds(int mr)
	{
		this.maxRounds =  mr;
	}
}
